name: Eric test
favicon: null
layout_spectrum: 0.52688
typography_spectrum: 0.32851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#94b7e9'
    - '#839c57'
    - '#3a3b37'
    - '#141411'
    - '#dedcc6'
  brandStrength: 0
  lightness: 0.14316475205123425
  saturation: 1
  rhythmicContrast: 1
purpose: []
