name: Eric test
favicon: null
layout_spectrum: 0.21291225287131965
typography_spectrum: 0.18466465082019567
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.549166165990755
  lightness: 0.14316475205123425
  saturation: 0.9632466395851225
  rhythmicContrast: 0.9062127184588462
purpose: []
